#!/usr/bin/env bash
# DIFF_BASELINE: bash
# Coverage: variable surface probe (core + bash extensions) by set/unset presence

set +e

vars='HOME PATH IFS PWD OLDPWD OPTIND OPTARG PS1 PS2 MAIL MAILPATH LANG LC_ALL LC_CTYPE LC_MESSAGES LINENO ENV BASH BASH_VERSION BASH_VERSINFO BASH_SOURCE BASH_LINENO BASH_COMMAND BASH_SUBSHELL BASHPID BASHOPTS SHELLOPTS BASH_COMPAT BASH_ENV BASH_ARGC BASH_ARGV BASH_ARGV0 BASH_CMDS BASH_REMATCH BASH_LOADABLES_PATH BASH_XTRACEFD EPOCHREALTIME EPOCHSECONDS RANDOM SECONDS SRANDOM EUID UID PPID GROUPS DIRSTACK FUNCNAME COPROC REPLY PROMPT_COMMAND PS0 PS3 PS4 COMP_LINE COMP_POINT COMP_WORDS COMP_CWORD COMP_WORDBREAKS COMP_TYPE COMP_KEY COMPREPLY HISTFILE HISTSIZE HISTFILESIZE HISTCONTROL HISTIGNORE HISTTIMEFORMAT HOSTFILE FCEDIT TMOUT'

for v in $vars; do
  if eval "test \"\\${$v+set}\" = set"; then
    echo "var:$v:set"
  else
    echo "var:$v:unset"
  fi
done
